### ISSUE TITLE
Unhandled exception: ERR_INVALID_ARG_TYPE during deployment

### ISSUE THREAD

**Issue by C-Collamar** [Jefiozie/ngx-aws-deploy#470]
**Describe the bug**

When I run `npx ng deploy`, I get the console error below.

```log
✔ Build Completed
An unhandled exception occurred: The "paths[0]" argument must be of type string. Received undefined
See "C:\Users\CHRIST~1\AppData\Local\Temp\ng-tAjEsr\angular-errors.log" for further details.
```

Checking `angular-errors.log` shows:

```log
[error] TypeError [ERR_INVALID_ARG_TYPE]: The "paths[0]" argument must be of type string. Received undefined
    at Object.resolve (node:path:171:9)
    at setopts (C:\Users\Christian\Documents\Workspace\hello-world\node_modules\glob\common.js:93:21)
    at new GlobSync (C:\Users\Christian\Documents\Workspace\hello-world\node_modules\glob\sync.js:37:3)
    at Function.globSync [as sync] (C:\Users\Christian\Documents\Workspace\hello-world\node_modules\glob\sync.js:23:10)
    at getFiles (C:\Users\Christian\Documents\Workspace\hello-world\node_modules\@jefiozie\ngx-aws-deploy\src\lib\deploy\index.js:10:17)
    at C:\Users\Christian\Documents\Workspace\hello-world\node_modules\@jefiozie\ngx-aws-deploy\src\lib\deploy\index.js:54:23
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\Christian\Documents\Workspace\hello-world\node_modules\tslib\tslib.js:166:62)
```
---
**To Reproduce**

1. Create a new Angular project.

   ```bash
   npx -p @angular/cli ng new hello-world --defaults
   ```
1. Add `@jefiozie/ngx-aws-deploy`.

   ```bash
   npx ng add @jefiozie/ngx-aws-deploy
   ```

   On a side note: running the command above only installs v4.1.0 of this package, instead of the v5.2.0 which is the latest release as of this writing.
1. Deploy. Environment variables don't need to be set to reproduce the issue.

   ```bash
   npx ng deploy
   ```
---
**Expected behavior**
I expect `npx ng deploy` to continue its attempt to deploy, until it fails with the following output as expected, since environment variables aren't set.

```log
❌  Missing authentication settings for AWS
❌  Missing authentication settings for AWS
```
---
**Screenshots**

![image](https://github.com/Jefiozie/ngx-aws-deploy/assets/19512843/b1c95d9f-7abc-4829-8e3d-c4315553e10c)
---
**Desktop (please complete the following information):**

- OS: Windows
- Browser: Google Chrome
- Version: 125.0.6422.77 (Official Build) (64-bit) (cohort: Stable)
---
**Additional context**

Digging deeper, here are my findings.

![image](https://github.com/Jefiozie/ngx-aws-deploy/assets/19512843/1854c7f3-2f7e-4ff3-be37-0662bea5fcfa)
![image](https://github.com/Jefiozie/ngx-aws-deploy/assets/19512843/e436657b-1834-4322-a262-703d3495346a)

1. The file in question is in `node_modules/@jefiozie/ngx-aws-deploy/src/lib/deploy/index.js`.
1. In no. 2 of the screenshots, the value of `architect_1.targetFromTargetString(buildTarget.name)` does not contain the `outputPath` property.
1. No `outputPath` property means that `getFiles(filesPath)` in no. 3 of the screenshot equals `getFiles(undefined)`. I think this causes the error.
1. No. 4 of the screenshot shows the workaround.

I find no. 2 suspicious, since `angular.json` has configured `projects.hello-world.architect.build.options.outputPath` to equal `"dist/hello-world"`. Even when I set `projects.hello-world.architect.build.configurations.production.outputPath`, no. 2 still does not "see" `outputPath`.

---
**Workaround**
Deploying, while circumventing the error involves a two-step process.
1. Manually build the application, with `npx ng build`.
1. Deploy without rebuidling, with `npx ng deploy --no-build`.

**Comment by rsinghania** [comment]
I m also facing same issue mentioned above.
